@startuml
!theme plain

left to right direction
skinparam packageStyle rectangle
actor 实习学生

rectangle 实习管理系统 {
  usecase (确认实习信息) as UC1
  usecase (修改登录密码) as UC2
  usecase (填报实习周记\n月记) as UC3
  usecase (提交实习总结) as UC4
  usecase (查看实习通知) as UC5
  usecase (提交请假单) as UC6
}

实习学生 --> UC1
实习学生 --> UC2
实习学生 --> UC3
实习学生 --> UC4
实习学生 --> UC5
实习学生 --> UC6

@enduml
