@startuml
!theme plain

frame "GPMS系统功能模块划分" {
    package "登录注册管理" {
        [管理员]
        [指导教师]
        [学生]
        [实习单位]
    }
    package "基本信息管理" {
        [指导教师信息管理]
        [学生信息管理]
        [实习单位信息管理]
    }
    package "实习成绩管理" {
        [提交周记/月记]
        [提交总结]
        [审核记录]
        [评分]
    }
    package "实习成绩管理" {
        [记录成绩]
        [更新成绩]
        [查询成绩]
    }
    package "实习评语管理" {
        [添加评语]
        [查看评语]
    }
    package "实习通知管理" {
        [发布通知（公告）]
        [清空通知（公告）]
    }
}

@enduml
