server:
  port: 8088
  servlet:
    context-path: /
    session:
      cookie:
        same-site: None
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    # specpwd needed
    password: MVYXGXCCFODXTENG
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    protocol: smtps
    username: banbang88@163.com
  # MySQL
  datasource:
    # MySQL8
    driver-class-name: com.mysql.cj.jdbc.Driver
    # mysql5 if needed
    #    driver-class-name: com.mysql.jdbc.Driver
    password: gpms87654321
    url: jdbc:mysql://banbang.ren:3306/cc_gpms_test?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: gpms
  data:
    #    elasticsearch:
    #      # ignore warning there: using previous version ES
    #      cluster-name: elasticsearch
    #      clusAer-nodes: ubd:9300
    redis:
      host: localhost
      database: 11
      port: 6379
  # kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-commit-interval: 3000
      enable-auto-commit: true
      group-id: test-consumer-group
# Mybatis-plus
mybatis-plus:
  configuration:
    # Turn on SQL logging on
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true
    useGeneratedKeys: true
  global-config:
    db-config:
      # set logic-delete
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: me.chang.gpms.pojo
wechat:
  applets:
    appid: wx7850d4bdeb683e5a
    secret: 71461445fa0f91c2204296f91758813c
swagger:
  #  enable: false
  enable: true
community:
  path:
    domain: http://localhost:8080
    editormdUploadPath: C:/Users/chang/Documents/Star/MyProject/Banbang/banbang-be/src/main/resources/static/editor-md-upload
caffeine:
  reports:
    expire-seconds: 180
    max-size: 15
