spring:
  profiles:
#    active: bb
#    active: dev
#    active: blank
    active: local
  datasource:
    hikari:
      max-lifetime: 500

logging:
  file:
    path: classpath:logback-spring-${spring.profiles.active}.xml
  pattern:
    console: "%clr(%d{MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"


